# Generated by Django 2.2.7 on 2020-03-05 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('max_posts', models.IntegerField()),
                ('post_duration', models.IntegerField()),
                ('is_premium', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='Maputo, Moçambique', max_length=150)),
                ('mobile', models.CharField(max_length=9)),
                ('mobile_alternative', models.CharField(max_length=9)),
                ('status', models.BooleanField(default=1)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.City')),
                ('package', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Package')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumb', models.CharField(default='avatar.jpg', max_length=255)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.IntegerField(default=0)),
                ('description', models.TextField(default='Ola! estou no SO Boladas...')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Category')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Seller')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(default='avatar.jpg', max_length=255)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Post')),
            ],
        ),
    ]
