# Generated by Django 2.2.7 on 2020-03-05 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='cash',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='seller',
            name='address',
            field=models.CharField(default='Moçambique', max_length=150),
        ),
        migrations.AlterField(
            model_name='seller',
            name='mobile_alternative',
            field=models.CharField(default='', max_length=9),
        ),
    ]
