# Generated by Django 2.2.7 on 2020-03-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20200306_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='total_posts',
            field=models.BooleanField(default=1),
        ),
    ]
