# Generated by Django 2.2.7 on 2020-03-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_seller_total_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='total_posts',
            field=models.IntegerField(default=1),
        ),
    ]
