# Generated by Django 2.2.7 on 2020-03-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20200306_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='total_posts',
            field=models.IntegerField(default=0),
        ),
    ]
