# Generated by Django 2.2.7 on 2020-03-06 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0007_auto_20200306_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='approved_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='seller',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
