# Generated by Django 2.2.7 on 2020-05-01 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_seller_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(default='avatar.jpg', max_length=255)),
                ('approved', models.BooleanField(default=False)),
                ('seller', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Seller')),
            ],
        ),
    ]
